---
title: "meta_plots"
author: "Yihan Wang"
date: "2025-09-16"
output: word_document
---

```{r}
rm(list=ls())
set.seed(42)
library(missRanger)
library(ggplot2)
library(tidyverse)
library(viridis)
library(pheatmap)
library(rlang)
library(psych)
```

```{r}
source("medication-lmer-utility.R")
source("plots.R")
```

```{r}
med_cols<-c("ACEi","ARB","BetaBlk","CCB","Diuretic","Metformin","Statin")
```

```{r}
NACC_full_df_mmse_imputed<-read.csv("../preprocessed_data/NACC/NACC_mmse_imputed_binary.csv")
AIBL_full_df_mmse_imputed<-read.csv("../preprocessed_data/AIBL/AIBL_mmse_imputed_binary.csv")
HABS_full_df_mmse_imputed<-read.csv("../preprocessed_data/HABSHD/HABSHD_mmse_imputed_binary.csv")
```

```{r}
p <- plot_med_corr_by_cohort(
  NACC_df = NACC_full_df_mmse_imputed,
  AIBL_df = AIBL_full_df_mmse_imputed,
  HABS_df = HABS_full_df_mmse_imputed,
  med_cols = med_cols,
  dataset_order = c("NACC","AIBL","HABS"),  # <- set your facet order
  method = "pearson",                       # or "tetrachoric"
  mask_upper_triangle = FALSE,
  out_pdf = "../plots/correlation/med_corr_by_cohort_mmse.pdf",
  width = 12, height = 4.2
)
print(p)
```

################## CDR Baseline medicaton#############
```{r}
NACC_full_df_cdr_imputed<-read.csv("../preprocessed_data/NACC/NACC_cdr_imputed_binary.csv")
AIBL_full_df_cdr_imputed<-read.csv("../preprocessed_data/AIBL/AIBL_cdr_imputed_binary.csv")
HABS_full_df_cdr_imputed<-read.csv("../preprocessed_data/HABSHD/HABSHD_cdr_imputed_binary.csv")
```

```{r}
p2 <- plot_med_corr_by_cohort(
  NACC_df = NACC_full_df_cdr_imputed,
  AIBL_df = AIBL_full_df_cdr_imputed,
  HABS_df = HABS_full_df_cdr_imputed,
  med_cols = med_cols,
  dataset_order = c("NACC","AIBL","HABS"),  # <- set your facet order
  method = "pearson",                       # or "tetrachoric"
  mask_upper_triangle = FALSE,
  out_pdf = "../plots/correlation/med_corr_by_cohort_cdr.pdf",
  width = 12, height = 4.2
)
print(p2)
```