---
title: "meta_plots"
author: "Yihan Wang"
date: "2025-09-16"
output: word_document
---

```{r}
rm(list=ls())
set.seed(42)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)
library(stringr)
library(scales)
```

```{r}
source("medication-lmer-utility.R")
source("plots.R")
```

```{r}
med_cols<-c("ACEi","ARB","BetaBlk","CCB","Diuretic","Statin","Metformin")
```

```{r}
NACC_full_df_mmse_imputed<-read.csv("../preprocessed_data/NACC/NACC_mmse_imputed_binary.csv")
AIBL_full_df_mmse_imputed<-read.csv("../preprocessed_data/AIBL/AIBL_mmse_imputed_binary.csv")
HABS_full_df_mmse_imputed<-read.csv("../preprocessed_data/HABSHD/HABSHD_mmse_imputed_binary.csv")
```

################## MMSE Baseline medicaton#############
```{r}
AIBL_full_df_mmse_imputed_baseline <- make_participant_summary(
  df            = AIBL_full_df_mmse_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "MMSE",
  out_col       = "dMMSE_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "baseline"
)

NACC_full_df_mmse_imputed_baseline <- make_participant_summary(
  df            = NACC_full_df_mmse_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "MMSE",
  out_col       = "dMMSE_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "baseline"
)

HABS_full_df_mmse_imputed_baseline <- make_participant_summary(
  df            = HABS_full_df_mmse_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "MMSE",
  out_col       = "dMMSE_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "baseline"
)
```

Medication exposure proportions at Baseline
Composite ‘Any medication’ = participant has ≥1 of the meds
```{r}
res <- baseline_props_to_pdf(
  NACC_df = NACC_full_df_mmse_imputed_baseline,
  AIBL_df = AIBL_full_df_mmse_imputed_baseline,
  HABS_df = HABS_full_df_mmse_imputed_baseline,
  out_pdf = "../plots/drug_usage/MMSE_baseline_drug_usage.pdf",
  width = 11, height = 4.2,     # absolute inches
  fill_values = c("Yes" = "#67a8cd", "No" = "#E68B81"),
  add_borders = TRUE,
  text_size = 8                  # smaller overall text
)
```

```{r}
baseline_table <- baseline_props_table(
  NACC_df = NACC_full_df_mmse_imputed_baseline,
  AIBL_df = AIBL_full_df_mmse_imputed_baseline,
  HABS_df = HABS_full_df_mmse_imputed_baseline,
  dataset_order = c("NACC","AIBL","HABS"),
  include_individual_meds = TRUE,
  include_any_med = TRUE,
  digits = 1
)
print(baseline_table)
```




################## MMSE Overall medicaton#############
```{r}
AIBL_full_df_mmse_imputed_overall <- make_participant_summary(
  df            = AIBL_full_df_mmse_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "MMSE",
  out_col       = "dMMSE_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "overall"
)

NACC_full_df_mmse_imputed_overall <- make_participant_summary(
  df            = NACC_full_df_mmse_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "MMSE",
  out_col       = "dMMSE_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "overall"
)

HABS_full_df_mmse_imputed_overall <- make_participant_summary(
  df            = HABS_full_df_mmse_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "MMSE",
  out_col       = "dMMSE_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "overall"
)
```

```{r}
res2 <- baseline_props_to_pdf(
  NACC_df = NACC_full_df_mmse_imputed_overall,
  AIBL_df = AIBL_full_df_mmse_imputed_overall,
  HABS_df = HABS_full_df_mmse_imputed_overall,
  out_pdf = "../plots/drug_usage/MMSE_overall_drug_usage.pdf",
  width = 11, height = 4.2,     # absolute inches
  fill_values = c("Yes" = "#67a8cd", "No" = "#E68B81"),
  add_borders = TRUE,
  text_size = 8                  # smaller overall text
)
```

```{r}
overall_table <- baseline_props_table(
  NACC_df = NACC_full_df_mmse_imputed_overall,
  AIBL_df = AIBL_full_df_mmse_imputed_overall,
  HABS_df = HABS_full_df_mmse_imputed_overall,
  dataset_order = c("NACC","AIBL","HABS"),
  include_individual_meds = TRUE,
  include_any_med = TRUE,
  digits = 1
)
print(overall_table)
```




```{r}
NACC_full_df_cdr_imputed<-read.csv("../preprocessed_data/NACC/NACC_cdr_imputed_binary.csv")
AIBL_full_df_cdr_imputed<-read.csv("../preprocessed_data/AIBL/AIBL_cdr_imputed_binary.csv")
HABS_full_df_cdr_imputed<-read.csv("../preprocessed_data/HABSHD/HABSHD_cdr_imputed_binary.csv")
```

################## MMSE Baseline medicaton#############
```{r}
AIBL_full_df_cdr_imputed_baseline <- make_participant_summary(
  df            = AIBL_full_df_cdr_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "CDR",
  out_col       = "dCDR_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "baseline"
)

NACC_full_df_cdr_imputed_baseline <- make_participant_summary(
  df            = NACC_full_df_cdr_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "CDR",
  out_col       = "dCDR_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "baseline"
)

HABS_full_df_cdr_imputed_baseline <- make_participant_summary(
  df            = HABS_full_df_cdr_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "CDR",
  out_col       = "dCDR_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "baseline"
)
```


```{r}
res3 <- baseline_props_to_pdf(
  NACC_df = NACC_full_df_cdr_imputed_baseline,
  AIBL_df = AIBL_full_df_cdr_imputed_baseline,
  HABS_df = HABS_full_df_cdr_imputed_baseline,
  out_pdf = "../plots/drug_usage/CDR_baseline_drug_usage.pdf",
  width = 11, height = 4.2,     # absolute inches
  fill_values = c("Yes" = "#67a8cd", "No" = "#E68B81"),
  add_borders = TRUE,
  text_size = 8                  # smaller overall text
)
```

```{r}
baseline_table2 <- baseline_props_table(
  NACC_df = NACC_full_df_cdr_imputed_baseline,
  AIBL_df = AIBL_full_df_cdr_imputed_baseline,
  HABS_df = HABS_full_df_cdr_imputed_baseline,
  dataset_order = c("NACC","AIBL","HABS"),
  include_individual_meds = TRUE,
  include_any_med = TRUE,
  digits = 1
)
print(baseline_table2)
```


################## MMSE Overall medicaton#############
```{r}
AIBL_full_df_cdr_imputed_overall <- make_participant_summary(
  df            = AIBL_full_df_cdr_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "CDR",
  out_col       = "dCDR_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "overall"
)

NACC_full_df_cdr_imputed_overall <- make_participant_summary(
  df            = NACC_full_df_cdr_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "CDR",
  out_col       = "dCDR_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "overall"
)

HABS_full_df_cdr_imputed_overall <- make_participant_summary(
  df            = HABS_full_df_cdr_imputed,
  id_col        = "id",
  time_col      = "months_since_baseline",
  visit_col     = "visit_no",   # or NULL if absent
  dataset_col   = NULL,         # <- optional
  value_col     = "CDR",
  out_col       = "dCDR_per_year",
  med_cols      = med_cols,
  demo_cols     = c("age","sex","APOE4","status"),
  collapse_mode = "overall"
)
```

```{r}
res4 <- baseline_props_to_pdf(
  NACC_df = NACC_full_df_cdr_imputed_overall,
  AIBL_df = AIBL_full_df_cdr_imputed_overall,
  HABS_df = HABS_full_df_cdr_imputed_overall,
  out_pdf = "../plots/drug_usage/CDR_overall_drug_usage.pdf",
  width = 11, height = 4.2,     # absolute inches
  fill_values = c("Yes" = "#67a8cd", "No" = "#E68B81"),
  add_borders = TRUE,
  text_size = 8                  # smaller overall text
)
```

```{r}
overall_table2 <- baseline_props_table(
  NACC_df = NACC_full_df_cdr_imputed_overall,
  AIBL_df = AIBL_full_df_cdr_imputed_overall,
  HABS_df = HABS_full_df_cdr_imputed_overall,
  dataset_order = c("NACC", "AIBL","HABS"),
  include_individual_meds = TRUE,
  include_any_med = TRUE,
  digits = 1
)
print(overall_table2)
```

