---
title: "meta_plots"
author: "Yihan Wang"
date: "2025-09-16"
output: word_document
---

```{r}
# rm(list=ls())
library(missRanger)
library(dplyr)
library(lubridate)
library(lme4)       # mixed models
library(lmerTest)   # p-values for lmer
library(splines)
library(conflicted)
library(broom.mixed)
library(dplyr)
library(stringr)
library(forcats)
library(ggplot2)
library(forestploter)
library(grid)
library(gridtext)
conflicts_prefer(dplyr::lag)
conflicts_prefer(lmerTest::lmer)
conflicts_prefer(dplyr::filter)
```

```{r}
source("medication-lmer-utility.R")
source("plots.R")
```

```{r}
NACC_full_df_cdr<-read.csv("../preprocessed_data/NACC/NACC_cdr_imputed.csv")
AIBL_full_df_cdr<-read.csv("../preprocessed_data/AIBL/AIBL_cdr_imputed.csv")
HABS_full_df_cdr<-read.csv("../preprocessed_data/HABSHD/HABSHD_cdr_imputed.csv")
NACC_full_df_cdr$edu <- scale(NACC_full_df_cdr$edu)
NACC_full_df_cdr$age <- scale(NACC_full_df_cdr$age)
AIBL_full_df_cdr$edu <- scale(AIBL_full_df_cdr$edu)
AIBL_full_df_cdr$age <- scale(AIBL_full_df_cdr$age)
HABS_full_df_cdr$edu <- scale(HABS_full_df_cdr$edu)
HABS_full_df_cdr$age <- scale(HABS_full_df_cdr$age)
```

```{r}
NACC_hc= split_by_baseline(NACC_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$HC
AIBL_hc= split_by_baseline(AIBL_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$HC
HABS_hc= split_by_baseline(HABS_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$HC
```


### CU
```{r}
NACC_hc$visit_date <- as.Date(NACC_hc$visit_date, format = "%Y-%m-%d")
fit_NACC_CU <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = NACC_hc
)
summary(fit_NACC_CU)
```


```{r}
AIBL_hc$visit_date <- as.Date(AIBL_hc$visit_date, format = "%Y-%m-%d")
fit_AIBL_CU <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = AIBL_hc
)
summary(fit_AIBL_CU)
```

```{r}
HABS_hc$visit_date <- as.Date(HABS_hc$visit_date, format = "%Y-%m-%d")
fit_HABS_CU <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = HABS_hc
)
summary(fit_HABS_CU)
```

# MCI
```{r}
NACC_mci= split_by_baseline(NACC_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$MCI
AIBL_mci= split_by_baseline(AIBL_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$MCI
HABS_mci= split_by_baseline(HABS_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$MCI
```

```{r}
NACC_mci$visit_date <- as.Date(NACC_mci$visit_date, format = "%Y-%m-%d")
fit_NACC_MCI <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = NACC_mci
)
summary(fit_NACC_MCI)
```

```{r}
AIBL_mci$visit_date <- as.Date(AIBL_mci$visit_date, format = "%Y-%m-%d")
fit_AIBL_MCI <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = AIBL_mci
)
summary(fit_AIBL_MCI)
```


```{r}
HABS_mci$visit_date <- as.Date(HABS_mci$visit_date, format = "%Y-%m-%d")
fit_HABS_MCI <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = HABS_mci
)
summary(fit_HABS_MCI)
```


# AD
```{r}
NACC_ad= split_by_baseline(NACC_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$AD
AIBL_ad= split_by_baseline(AIBL_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$AD
HABS_ad= split_by_baseline(HABS_full_df_cdr, id_col = "id", visit_col = "visit_no", status_col = "status")$AD
```

```{r}
NACC_ad$visit_date <- as.Date(NACC_ad$visit_date, format = "%Y-%m-%d")
fit_NACC_AD <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = NACC_ad
)
summary(fit_NACC_AD)
```

```{r}
AIBL_ad$visit_date <- as.Date(AIBL_ad$visit_date, format = "%Y-%m-%d")
fit_AIBL_AD <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = AIBL_ad
)
summary(fit_AIBL_AD)
```


```{r}
HABS_ad$visit_date <- as.Date(HABS_ad$visit_date, format = "%Y-%m-%d")
fit_HABS_AD <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = HABS_ad
)
summary(fit_HABS_AD)
```



# plots
```{r}
terms_all <-c(
    "year_since_baseline","age","sex","edu","APOE4",
    "ACEiTrue","ARBTrue","BetaBlkTrue","CCBTrue",
    "DiureticTrue","MetforminTrue", "StatinTrue",
    "year_since_baseline:ACEiTrue","year_since_baseline:ARBTrue",
    "year_since_baseline:BetaBlkTrue","year_since_baseline:CCBTrue",
    "year_since_baseline:DiureticTrue", "year_since_baseline:MetforminTrue",
    "year_since_baseline:StatinTrue"
  )
terms_rename <- c(
    "year_since_baseline"="Time",
    "age"="Age (baseline)",
    "sex"="Sex (ref: Male)",
    "edu"="Education (z-scored)",
    "APOE4"="APOE4 carrier (ref: No)",
    "ACEiTrue"="ACEi",
    "ARBTrue"="ARBs",
    "BetaBlkTrue"="β-Blocker",
    "CCBTrue"="CCBs",
    "DiureticTrue"="Diuretics",
    "MetforminTrue"="Metformin",
    "StatinTrue"="Statins",
    "year_since_baseline:ACEiTrue"="ACEi × Time",
    "year_since_baseline:ARBTrue"="ARBs × Time",
    "year_since_baseline:BetaBlkTrue"="β-Blocker × Time",
    "year_since_baseline:CCBTrue"="CCBs × Time",
    "year_since_baseline:DiureticTrue"="Diuretics × Time",
    "year_since_baseline:MetforminTrue"="Metformin × Time",
    "year_since_baseline:StatinTrue"="Statins × Time"
  )
```


```{r}
plot_forest_subset_meta_expanded(
  fits = list(
    CU     = list(fit_NACC_CU,   fit_AIBL_CU,   fit_HABS_CU),
    MCI   = list(fit_NACC_MCI,   fit_AIBL_MCI,   fit_HABS_MCI),
    AD     = list(fit_NACC_AD,   fit_AIBL_AD,   fit_HABS_AD)
  ),
  terms         = terms_all,
  groups       = c("CU","MCI","AD"),
  cohorts       = c("NACC","AIBL","HABS-HD"),
  term_labels   = terms_rename,
  title         = "",
  filename      = "../plots/forestplot/CDR_forestplot_cognition_longitudinal.pdf",
  width         = 20, height = 12,
  ref_line      = 0,
  # xlim_fixed    = c(-0.25, 0.25),
  xlim_per_group = list(
  CU = c(-0.05, 0.05),
  MCI = c(-0.2, 0.2),
  AD = c(-0.2, 0.2)
),
  cohort_colors = c("#DAA87C", "#92A5D1", "#C9DCC4"),
  cohort_shapes = c(15, 16, 18),
  IF_META_ANALYSIS = TRUE, meta_label = "Meta", meta_color = "#fe6666", meta_shape = 17,
  row_padding_mm = 6, lineheight_txt = 0.05,
  point_size = 0.85, line_width = 2.8,
  # ABSOLUTE widths in INCHES (not fractions!)
  add_gutter = TRUE,gutter_width=0.10,
  # gutter_width = 0.2,       # 0.5 inches between groups
  first_col_width = 3.5,    # 3.5 inches for Measurements
  est_frac = 3.0,           # 2.5 inches for Estimate (SE)
  wgt_frac = 2.0,           # 1.5 inches for Weight
  ci_frac = 8.0,            # 8 inches for CI plot (WIDE!)
  block_col1 = "#f8f1ff", block_col2 = "#FFFFFF",
  p_adjust = 'BH',
  feature_subset=c("year_since_baseline:ACEiTrue","year_since_baseline:ARBTrue",
    "year_since_baseline:BetaBlkTrue","year_since_baseline:CCBTrue",
    "year_since_baseline:DiureticTrue", "year_since_baseline:MetforminTrue",
    "year_since_baseline:StatinTrue")
)

```



```{r}
dt_cog = make_dt_from_fits(
  fits = list(
    CU     = list(fit_NACC_CU,   fit_AIBL_CU,   fit_HABS_CU),
    MCI   = list(fit_NACC_MCI,   fit_AIBL_MCI,   fit_HABS_MCI),
    AD     = list(fit_NACC_AD,   fit_AIBL_AD,   fit_HABS_AD)
  ),
  term= terms_all,
  cohorts = c("NACC","AIBL","HABS"),
  term_labels  = terms_rename,
  method = "REML",
  digits = 3,
  p_adjust = "BH"
)
```