---
title: "meta_plots"
author: "Yihan Wang"
date: "2025-09-16"
output: word_document
---

```{r}
# rm(list=ls())
library(missRanger)
library(dplyr)
library(lubridate)
library(lme4)       # mixed models
library(lmerTest)   # p-values for lmer
library(splines)
library(conflicted)
library(broom.mixed)
library(dplyr)
library(stringr)
library(forcats)
library(ggplot2)
library(forestploter)
library(grid)
library(gridtext)
conflicts_prefer(dplyr::lag)
conflicts_prefer(lmerTest::lmer)
conflicts_prefer(dplyr::filter)
```

```{r}
source("medication-lmer-utility.R")
source("plots.R")
```

```{r}
NACC_full_df_cdr<-read.csv("../preprocessed_data/NACC/NACC_cdr_imputed.csv")
AIBL_full_df_cdr<-read.csv("../preprocessed_data/AIBL/AIBL_cdr_imputed.csv")
HABS_full_df_cdr<-read.csv("../preprocessed_data/HABSHD/HABSHD_cdr_imputed.csv")
NACC_full_df_cdr$edu <- scale(NACC_full_df_cdr$edu)


NACC_full_df_cdr$age <- scale(NACC_full_df_cdr$age)
AIBL_full_df_cdr$edu <- scale(AIBL_full_df_cdr$edu)
AIBL_full_df_cdr$age <- scale(AIBL_full_df_cdr$age)
HABS_full_df_cdr$edu <- scale(HABS_full_df_cdr$edu)
HABS_full_df_cdr$age <- scale(HABS_full_df_cdr$age)
```

# Main
### FUll
```{r}
NACC_full_df_cdr$visit_date <- as.Date(NACC_full_df_cdr$visit_date, format = "%Y-%m-%d")
fit_full_NACC <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = NACC_full_df_cdr
)
summary(fit_full_NACC)
```

```{r}
p.adjust(coef(summary(fit_full_NACC))[,"Pr(>|t|)"], method="BH")
```


```{r}
AIBL_full_df_cdr$visit_date <- as.Date(AIBL_full_df_cdr$visit_date, format = "%Y-%m-%d")
fit_full_AIBL <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = AIBL_full_df_cdr
)
summary(fit_full_AIBL)
```
```{r}
p.adjust(coef(summary(fit_full_AIBL))[,"Pr(>|t|)"], method="BH")
```


```{r}
HABS_full_df_cdr$visit_date <- as.Date(HABS_full_df_cdr$visit_date, format = "%Y-%m-%d")
fit_full_HABS <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = HABS_full_df_cdr
)
summary(fit_full_HABS)
```

```{r}
p.adjust(coef(summary(fit_full_HABS))[,"Pr(>|t|)"], method="BH")
```

# Gender Stratficaton
```{r}
NACC_male = NACC_full_df_cdr[NACC_full_df_cdr$sex == 0, ]
NACC_female = NACC_full_df_cdr[NACC_full_df_cdr$sex == 1, ]
AIBL_male = AIBL_full_df_cdr[AIBL_full_df_cdr$sex == 0, ]
AIBL_female = AIBL_full_df_cdr[AIBL_full_df_cdr$sex == 1, ]
HABS_male = HABS_full_df_cdr[HABS_full_df_cdr$sex == 0, ]
HABS_female = HABS_full_df_cdr[HABS_full_df_cdr$sex == 1, ]
```

```{r}
NACC_female$visit_date <- as.Date(NACC_female$visit_date, format = "%Y-%m-%d")
fit_female_NACC <- lmer(
  CDR ~ year_since_baseline +
    age + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = NACC_female
)
summary(fit_female_NACC)
```

```{r}
NACC_male$visit_date <- as.Date(NACC_male$visit_date, format = "%Y-%m-%d")
fit_male_NACC <- lmer(
  CDR ~ year_since_baseline +
    age + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = NACC_male
)
summary(fit_male_NACC)
```


```{r}
AIBL_female$visit_date <- as.Date(AIBL_female$visit_date, format = "%Y-%m-%d")
fit_female_AIBL <- lmer(
  CDR ~ year_since_baseline +
    age + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = AIBL_female
)
summary(fit_female_AIBL)
```

```{r}
AIBL_male$visit_date <- as.Date(AIBL_male$visit_date, format = "%Y-%m-%d")
fit_male_AIBL <- lmer(
  CDR ~ year_since_baseline +
    age + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic +  Metformin + Statin +
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = AIBL_male
)
summary(fit_male_AIBL)
```


```{r}
HABS_female$visit_date <- as.Date(HABS_female$visit_date, format = "%Y-%m-%d")
fit_female_HABS <- lmer(
  CDR ~ year_since_baseline +
    age + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic +  Metformin + Statin +
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = HABS_female
)
summary(fit_female_HABS)
```

```{r}
HABS_male$visit_date <- as.Date(HABS_male$visit_date, format = "%Y-%m-%d")
fit_male_HABS <- lmer(
  CDR ~ year_since_baseline +
    age + edu + APOE4 +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = HABS_male
)
summary(fit_male_HABS)
```

# APOE Stratficaton
```{r}
NACC_APOEY = NACC_full_df_cdr[NACC_full_df_cdr$APOE4 == 1, ]
NACC_APOEN = NACC_full_df_cdr[NACC_full_df_cdr$APOE4 == 0, ]
AIBL_APOEY = AIBL_full_df_cdr[AIBL_full_df_cdr$APOE4 == 1, ]
AIBL_APOEN = AIBL_full_df_cdr[AIBL_full_df_cdr$APOE4 == 0, ]
HABS_APOEY = HABS_full_df_cdr[HABS_full_df_cdr$APOE4 == 1, ]
HABS_APOEN = HABS_full_df_cdr[HABS_full_df_cdr$APOE4 == 0, ]
```

```{r}
NACC_APOEY$visit_date <- as.Date(NACC_APOEY$visit_date, format = "%Y-%m-%d")
fit_APOEY_NACC <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = NACC_APOEY
)
summary(fit_APOEY_NACC)
```

```{r}
NACC_APOEN$visit_date <- as.Date(NACC_APOEN$visit_date, format = "%Y-%m-%d")
fit_APOEN_NACC <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = NACC_APOEN
)
summary(fit_APOEN_NACC)
```

```{r}
AIBL_APOEY$visit_date <- as.Date(AIBL_APOEY$visit_date, format = "%Y-%m-%d")
fit_APOEY_AIBL <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = AIBL_APOEY
)
summary(fit_APOEY_AIBL)
```

```{r}
AIBL_APOEN$visit_date <- as.Date(AIBL_APOEN$visit_date, format = "%Y-%m-%d")
fit_APOEN_AIBL <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = AIBL_APOEN
)
summary(fit_APOEN_AIBL)
```

```{r}
HABS_APOEY$visit_date <- as.Date(HABS_APOEY$visit_date, format = "%Y-%m-%d")
fit_APOEY_HABS <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = HABS_APOEY
)
summary(fit_APOEY_HABS)
```

```{r}
HABS_APOEN$visit_date <- as.Date(HABS_APOEN$visit_date, format = "%Y-%m-%d")
fit_APOEN_HABS <- lmer(
  CDR ~ year_since_baseline +
    age + sex + edu +
    ACEi + ARB + BetaBlk + CCB + Diuretic + Metformin + Statin + 
    ACEi:year_since_baseline + ARB:year_since_baseline + BetaBlk:year_since_baseline +
    CCB:year_since_baseline + Diuretic:year_since_baseline + 
    Metformin:year_since_baseline + Statin:year_since_baseline +
    (1 + year_since_baseline | id),
  data = HABS_APOEN
)
summary(fit_APOEN_HABS)
```


```{r}
terms_all <-c(
    "year_since_baseline","age","sex","edu","APOE4",
    "ACEiTrue","ARBTrue","BetaBlkTrue","CCBTrue",
    "DiureticTrue","MetforminTrue", "StatinTrue",
    "year_since_baseline:ACEiTrue","year_since_baseline:ARBTrue",
    "year_since_baseline:BetaBlkTrue","year_since_baseline:CCBTrue",
    "year_since_baseline:DiureticTrue", "year_since_baseline:MetforminTrue",
    "year_since_baseline:StatinTrue"
  )
terms_rename <- c(
    "year_since_baseline"="Time",
    "age"="Age (baseline)",
    "sex"="Sex (ref: Male)",
    "edu"="Education (z-scored)",
    "APOE4"="APOE4 carrier (ref: No)",
    "ACEiTrue"="ACEi",
    "ARBTrue"="ARBs",
    "BetaBlkTrue"="β-Blocker",
    "CCBTrue"="CCBs",
    "DiureticTrue"="Diuretics",
    "MetforminTrue"="Metformin",
    "StatinTrue"="Statins",
    "year_since_baseline:ACEiTrue"="ACEi × Time",
    "year_since_baseline:ARBTrue"="ARBs × Time",
    "year_since_baseline:BetaBlkTrue"="β-Blocker × Time",
    "year_since_baseline:CCBTrue"="CCBs × Time",
    "year_since_baseline:DiureticTrue"="Diuretics × Time",
    "year_since_baseline:MetforminTrue"="Metformin × Time",
    "year_since_baseline:StatinTrue"="Statins × Time"
  )
```


```{r}
plot_forest_subset_meta_expanded(
  fits = list(
    Full     = list(fit_full_NACC,   fit_full_AIBL,   fit_full_HABS),
    Female   = list(fit_female_NACC, fit_female_AIBL, fit_female_HABS),
    Male     = list(fit_male_NACC,   fit_male_AIBL,   fit_male_HABS),
    `APOE4 carriers`     = list(fit_APOEY_NACC,  fit_APOEY_AIBL,  fit_APOEY_HABS),
    `APOE4 non-carriers` = list(fit_APOEN_NACC,  fit_APOEN_AIBL,  fit_APOEN_HABS)
  ),
  terms         = terms_all,
  groups        = c("Full","Female","Male","APOE4 carriers","APOE4 non-carriers"),
  cohorts       = c("NACC","AIBL","HABS-HD"),
  term_labels   = terms_rename,
  title         = "",
  filename      = "../plots/forestplot/CDR_forestplot_main_baseline.pdf",
  width         = 31, height = 12,
  ref_line      = 0,
  # xlim_fixed    = c(-0.8, 0.8),
  xlim_per_group = list(
  Full = c(-0.4, 0.4),
  Female = c(-0.5, 0.5),
  Male = c(-0.5, 0.5),
  "APOE4 carriers" = c(-0.5, 0.5),
  "APOE4 non-carriers" = c(-0.4, 0.4)
),
  cohort_colors = c("#DAA87C", "#92A5D1", "#C9DCC4"),
  cohort_shapes = c(15, 16, 18),
  IF_META_ANALYSIS = TRUE, meta_label = "Meta", meta_color = "#fe6666", meta_shape = 17,
  row_padding_mm = 6, lineheight_txt = 0.05,
  point_size = 0.8, line_width = 2.8,
  # ABSOLUTE widths in INCHES (not fractions!)
  add_gutter = TRUE,gutter_width=0.10,
  # gutter_width = 0.2,       # 0.5 inches between groups
  first_col_width = 3.5,    # 3.5 inches for Measurements
  est_frac = 3.0,           # 2.5 inches for Estimate (SE)
  wgt_frac = 2.0,           # 1.5 inches for Weight
  ci_frac = 8.0,            # 8 inches for CI plot (WIDE!)
  block_col1 = "#f8f1ff", block_col2 = "#FFFFFF",
  p_adjust = 'BH',
  feature_subset=c("ACEiTrue","ARBTrue","BetaBlkTrue","CCBTrue","DiureticTrue","MetforminTrue", "StatinTrue")
)
```
```{r}
plot_forest_subset_meta_expanded(
  fits = list(
    Full     = list(fit_full_NACC,   fit_full_AIBL,   fit_full_HABS),
    Female   = list(fit_female_NACC, fit_female_AIBL, fit_female_HABS),
    Male     = list(fit_male_NACC,   fit_male_AIBL,   fit_male_HABS),
    `APOE4 carriers`     = list(fit_APOEY_NACC,  fit_APOEY_AIBL,  fit_APOEY_HABS),
    `APOE4 non-carriers` = list(fit_APOEN_NACC,  fit_APOEN_AIBL,  fit_APOEN_HABS)
  ),
  terms         = terms_all,
  groups        = c("Full","Female","Male","APOE4 carriers","APOE4 non-carriers"),
  cohorts       = c("NACC","AIBL","HABS-HD"),
  term_labels   = terms_rename,
  title         = "",
  filename      = "../plots/forestplot/CDR_forestplot_main_longitudinal.pdf",
  width         = 31, height = 12,
  ref_line      = 0,
  # xlim_fixed    = c(-0.2, 0.2),
  xlim_per_group = list(
  Full = c(-0.1, 0.1),
  Female = c(-0.1, 0.1),
  Male = c(-0.1, 0.1),
  "APOE4 carriers" = c(-0.1, 0.1),
  "APOE4 non-carriers" = c(-0.1, 0.1)
),
  cohort_colors = c("#DAA87C", "#92A5D1", "#C9DCC4"),
  cohort_shapes = c(15, 16, 18),
  IF_META_ANALYSIS = TRUE, meta_label = "Meta", meta_color = "#fe6666", meta_shape = 17,
  row_padding_mm = 6, lineheight_txt = 0.05,
  point_size = 0.85, line_width = 2.8,
  # ABSOLUTE widths in INCHES (not fractions!)
  add_gutter = TRUE,gutter_width=0.10,
  # gutter_width = 0.2,       # 0.5 inches between groups
  first_col_width = 3.5,    # 3.5 inches for Measurements
  est_frac = 3.0,           # 2.5 inches for Estimate (SE)
  wgt_frac = 2.0,           # 1.5 inches for Weight
  ci_frac = 8.0,            # 8 inches for CI plot (WIDE!)
  block_col1 = "#f8f1ff", block_col2 = "#FFFFFF",
  p_adjust = 'BH',
  feature_subset=c("year_since_baseline:ACEiTrue","year_since_baseline:ARBTrue",
    "year_since_baseline:BetaBlkTrue","year_since_baseline:CCBTrue",
    "year_since_baseline:DiureticTrue", "year_since_baseline:MetforminTrue",
    "year_since_baseline:StatinTrue")
)
```
```{r}
dt_ = make_dt_from_fits(
  fits = list(
    Full     = list(fit_full_NACC,   fit_full_AIBL,   fit_full_HABS),
    Female   = list(fit_female_NACC, fit_female_AIBL, fit_female_HABS),
    Male     = list(fit_male_NACC,   fit_male_AIBL,   fit_male_HABS),
    `APOE4 carriers` = list(fit_APOEY_NACC,  fit_APOEY_AIBL,  fit_APOEY_HABS),
    `APOE4 non-carriers` = list(fit_APOEN_NACC,  fit_APOEN_AIBL,  fit_APOEN_HABS)
  ),
  term= terms_all,
  cohorts = c("NACC","AIBL","HABS"),
  term_labels  = terms_rename,
  method = "REML",
  digits = 3, 
  p_adjust = "BH"
)
```

```{r}
dt_t = make_dt_from_fits(
  fits = list(
    Full     = list(fit_full_NACC,   fit_full_AIBL,   fit_full_HABS),
    Female   = list(fit_female_NACC, fit_female_AIBL, fit_female_HABS),
    Male     = list(fit_male_NACC,   fit_male_AIBL,   fit_male_HABS),
    `APOE4 carriers` = list(fit_APOEY_NACC,  fit_APOEY_AIBL,  fit_APOEY_HABS),
    `APOE4 non-carriers` = list(fit_APOEN_NACC,  fit_APOEN_AIBL,  fit_APOEN_HABS)
  ),
  term= terms_all,
  cohorts = c("NACC","AIBL","HABS"),
  term_labels  = terms_rename,
  method = "REML",
  digits = 3, 
  p_adjust = "none"
)
```
